main/urls.py
from django.urls import include, path
from . import views

app_name = "main_app"

urlpatterns = [
    path('', views.index, name='home')
]

tortillasite/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls', namespace="")),
    path('movies', include('movies.urls')),
    path('celebrities', include('celebrities.urls')),
    path('users', include('users.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from movies.models import MovieGenre, TheMovie
from celebrities.models import Actor
from django.http import HttpResponse


# Create your views here.
def index(request):
    all_movies = TheMovie.objects.all()
    # for one_movie in all_movies:
    #     print(one_movie.genres.all())
    five_celebrities = Actor.objects.all()[:5]
    # print(five_actors)
    # current_user_username = request.session.get("current_user_username")
    errors = {}
    if request.session.get("login_error"):
        print(request.session.get("login_error"))
        errors["login_error"] = request.session["login_error"]
        del request.session["login_error"]
        # ensuring that everything is okey
        request.session.modified = True
        request.session.save()

    if request.session.get("signup_error"):
        print(request.session.get("signup_error"))
        errors["signup_error"] = request.session["signup_error"]
        del request.session["signup_error"]
        # ensuring that everything is okey
        request.session.modified = True
        request.session.save()
    return render(request, 'main/index.html',
                  {"all_movies": all_movies, "selected_celebrities": five_celebrities} | errors)

main/templates/main/layout.html
{% load static %}

<!DOCTYPE html>
<!--[if IE 7]>
<html class="ie ie7 no-js" lang="en-US">
<![endif]-->
<!--[if IE 8]>
<html class="ie ie8 no-js" lang="en-US">
<![endif]-->
<!--[if !(IE 7) | !(IE 8)  ]><!-->
<html lang="en" class="no-js">


<head>
	<!-- Basic need -->
	<title>{%block title%}{% endblock %}</title>
	<meta charset="UTF-8">
	<meta name="description" content="">
	<meta name="keywords" content="">
	<meta name="author" content="">
	<link rel="profile" href="#">

    <!--Google Font-->
    <link rel="stylesheet" href='http://fonts.googleapis.com/css?family=Dosis:400,700,500|Nunito:300,400,600' />
	<!-- Mobile specific meta -->
	<meta name=viewport content="width=device-width, initial-scale=1">
	<meta name="format-detection" content="telephone-no">

	<!-- CSS files -->
	<link rel="stylesheet" href="{% static 'main/css/plugins.css'%}">
	<link rel="stylesheet" href="{% static 'main/css/style.css'%}">
	<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
<div id="preloader">
    <img class="logo" src="{% static 'main/images/logo1.png'%}" alt="" width="119" height="58">
    <div id="status">
        <span></span>
        <span></span>
    </div>
</div>
<!--end of preloading-->
<!--login form popup-->
<div class="login-wrapper" id="login-content">
    <div class="login-content">
        <a href="#" class="close">x</a>
		{% if login_error %}
		<h3 style="margin-bottom:20px">Login</h3>
		<h4 style="color:darkred;text-align:center;margin-bottom:5px">{{ login_error|title }}!</h4>
		{% else %}
		<h3>Login</h3>
		{% endif %}
        <form method="post" action="{% url 'user_login' %}">
			{% csrf_token %}
        	<div class="row">
        		 <label for="username">
                    Username:
                    <input type="text" name="username" id="username" placeholder="" pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{4,20}$" required="required" />
                </label>
        	</div>

            <div class="row">
            	<label for="password">
                    Password:
                    <input type="password" name="password" id="password" placeholder="" pattern="(?=^.{4,}$).*$" required="required" />
                </label>
            </div>
            <div class="row">
            	<div class="remember">
					<div>
						<input type="checkbox" name="remember" value="Remember me"><span>Remember me</span>
					</div>
            		<a href="#">Forget password ?</a>
            	</div>
            </div>
           <div class="row">
           	 <button type="submit">Login</button>
           </div>
        </form>
        <div class="row">
        	<p>Or via social</p>
            <div class="social-btn-2">
            	<a class="fb" href="#"><i class="ion-social-facebook"></i>Facebook</a>
            	<a class="tw" href="#"><i class="ion-social-twitter"></i>twitter</a>
            </div>
        </div>
    </div>
</div>
<!--end of login form popup-->
<!--signup form popup-->
<div class="login-wrapper"  id="signup-content">
    <div class="login-content">
        <a href="#" class="close">x</a>
		{% if signup_error %}
		<h3 style="margin-bottom:20px">sign up</h3>
		<h4 style="color:darkred;text-align:center;margin-bottom:5px">{{ signup_error }}!</h4>
		{% else %}
		<h3>sign up</h3>
		{% endif %}
        <form method="post" action="{% url 'user_registration' %}">
			{% csrf_token %}
            <div class="row">
                 <label for="username-2">
                    Username: <span style="color:gray;font-size:10px">(minimum 5 symbols, the first is letter)</span>
                    <input type="text" name="username" id="username-2" placeholder="" pattern="^[a-zA-Z][a-zA-Z0-9-_\.]{4,20}$" required="required" maxlength="20"/>
                </label>
            </div>

            <div class="row">
                <label for="email-2">
                    your email: <span style="color:gray;font-size:10px">(minimum 5 symbols, the first is letter)</span>
                    <input type="email" name="email" id="email-2" placeholder="" pattern="(?=^.{5,}$)(?![.\n]).*$" required="required" />
                </label>
            </div>
             <div class="row">
                <label for="password-2">
                    Password: <span style="color:gray;font-size:10px">(minimum 4 symbols)</span>
                    <input type="password" name="password" id="password-2" placeholder="" pattern="(?=^.{4,}$).*$" required="required" />
                </label>
            </div>
             <div class="row">
                <label for="repassword-2">
                    re-type Password: <span style="color:gray;font-size:10px">(minimum 4 symbols)</span>
                    <input type="password" name="password" id="repassword-2" placeholder="" pattern="(?=^.{4,}$).*$" required="required" />
                </label>
            </div>
           <div class="row">
             <button type="submit">sign up</button>
           </div>
        </form>
    </div>
</div>
<!--end of signup form popup-->

<!-- BEGIN | Header -->
<header class="ht-header">
	<div class="container">
		<nav class="navbar navbar-default navbar-custom">
				<!-- Brand and toggle get grouped for better mobile display -->
				<div class="navbar-header logo">
				    <div class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					    <span class="sr-only">Toggle navigation</span>
					    <div id="nav-icon1">
							<span></span>
							<span></span>
							<span></span>
						</div>
				    </div>
				    <a href="{% url 'main_app:home' %}"><img class="logo" src="{% static 'main/images/logo1.png'%}" alt="" width="119" height="58"></a>
			    </div>
				<!-- Collect the nav links, forms, and other content for toggling -->
				<div class="collapse navbar-collapse flex-parent" id="bs-example-navbar-collapse-1">
					<ul class="nav navbar-nav flex-child-menu menu-left">
						<li class="hidden">
							<a href="#page-top"></a>
						</li>

						<li>
							<a href="{% url 'movies' %}">
							movies
							</a>
						</li>
						<li >
							<a href="{% url 'celebrities' %}">
							celebrities
							</a>

						</li>
						<li>
							<a href="#">
							news
							</a>
						</li>
						{% if request.session.current_user_username %}
						<li >
							<a href="{% url 'user_profile' %}">
							user profile
							</a>
						</li>
						{% endif %}
					</ul>
					<ul class="nav navbar-nav flex-child-menu menu-right">
						{% if request.session.current_user_username %}
							<li><a href="{% url 'user_profile' %}">Hello,
								{% if request.session.current_user_first_name and request.session.current_user_last_name %}
								{{ request.session.current_user_first_name }} {{ request.session.current_user_last_name }}
								{% else %}
								{{ request.session.current_user_username }}
								{% endif %}</a></li>
							<li class="btn logoutLink"><a href="{% url 'user_logout' %}">log out</a></li>
						{% else %}
							<li class="loginLink"><a href="">LOG In</a></li>
							<li class="btn signupLink"><a href="">sign up</a></li>
						{% endif %}
					</ul>
				</div>
			<!-- /.navbar-collapse -->
	    </nav>
	</div>
</header>
<!-- END | Header -->
{%block content %}{% endblock %}

<!-- footer section-->
<footer class="ht-footer">
	<div class="container">
		<div class="flex-parent-ft">
			<div class="flex-child-ft item1">
				 <a href="index.html"><img class="logo" src="{% static 'main/images/logo1.png'%}" alt=""></a>
				 <p>5th Avenue st, manhattan<br>
				New York, NY 10001</p>
				<p>Call us: <a href="#">(+01) 202 342 6789</a></p>
			</div>
			<div class="flex-child-ft item2">
				<h4>Resources</h4>
				<ul>
					<li><a href="#">About</a></li>
					<li><a href="#">Blockbuster</a></li>
					<li><a href="#">Contact Us</a></li>
					<li><a href="#">Forums</a></li>
					<li><a href="#">Blog</a></li>
					<li><a href="#">Help Center</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item3">
				<h4>Legal</h4>
				<ul>
					<li><a href="#">Terms of Use</a></li>
					<li><a href="#">Privacy Policy</a></li>
					<li><a href="#">Security</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item4">
				<h4>Account</h4>
				<ul>
					<li><a href="#">My Account</a></li>
					<li><a href="#">Watchlist</a></li>
					<li><a href="#">Collections</a></li>
					<li><a href="#">User Guide</a></li>
				</ul>
			</div>
			<div class="flex-child-ft item5">
				<h4>Newsletter</h4>
				<p>Subscribe to our newsletter system now <br> to get latest news from us.</p>
				<form action="#">
					<input type="text" placeholder="Enter your email...">
				</form>
				<a href="#" class="btn">Subscribe now <i class="ion-ios-arrow-forward"></i></a>
			</div>
		</div>
	</div>
</footer>
<script src="{% static 'main/js/jquery.js'%}"></script>
<script src="{% static 'main/js/plugins.js'%}"></script>
<script src="{% static 'main/js/plugins2.js'%}"></script>
<script src="{% static 'main/js/custom.js'%}"></script>
<script type="text/javascript">
	var loginct = $( "#login-content" );
	var signupct= $("#signup-content");
	var overlay = $(".overlay");

	{% if login_error %}
	$(document).ready(function() {
    	loginct.parents(overlay).addClass("openform");
		$(document).on('click', function(e){
		var target = $(e.target);
		if ($(target).hasClass("overlay")){
			$(target).find(loginct).each( function(){
				$(this).removeClass("openform");
			});
			setTimeout( function(){
				$(target).removeClass("openform");
			}, 350);
			}
		});
    });
    {% endif %}
    {% if signup_error %}
    $(document).ready(function() {
    	signupct.parents(overlay).addClass("openform");
		$(document).on('click', function(e){
		var target = $(e.target);
		if ($(target).hasClass("overlay")){
				$(target).find(signupct).each( function(){
					$(this).removeClass("openform");
				});
				setTimeout( function(){
					$(target).removeClass("openform");
				}, 350);
			}
		});
    });
    {% endif %}
 </script>
</body>
</html>